size = 1;
button_width = pointer_null; //120
button_height = pointer_null; //30
button_text = pointer_null;
button_x = pointer_null;
button_y = pointer_null;
mouse_hover = false;
button_clicked = false;
show_button = true;
text_offset_color = c_black;
is_toggled = false;
activated_toggle = false;
does_untoggle = true;