button_x_scale = 1;
button_y_scale = 1;
button_width = 80 * button_x_scale;
button_height = 30 * button_y_scale;
button_text = pointer_null;
button_x = pointer_null;
button_y = pointer_null;
mouse_hover = false;
button_clicked = false;